require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EducationsController do

  # This should return the minimal set of attributes required to create a valid
  # Education. As you add validations to Education, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {
        :country=>"india",:course=>"B.Sc",:level=>"graduation",:school_name=>"sree",:school_type=>"goverment",:state=>'kerala',:resume_id=>2
    }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EducationsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET new" do
    it "assigns a new education as @education" do
      get :new, {}, valid_session
      assigns(:education).should be_a_new(Education)
    end
  end

   describe "POST create" do
    describe "with valid params" do
      it "creates a new Education" do
        expect {
          post :create, {:education => valid_attributes}, valid_session
        }.to change(Education, :count).by(1)
      end

      it "assigns a newly created education as @education" do
        post :create, {:education => valid_attributes}, valid_session
        assigns(:education).should be_a(Education)
        assigns(:education).should be_persisted
      end

      it "redirects to the created education" do
        post :create, {:education => valid_attributes}, valid_session
        response.should redirect_to(new_education_path)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved education as @education" do
        # Trigger the behavior that occurs when invalid params are submitted
        Education.any_instance.stub(:save).and_return(false)
        post :create, {:education => {}}, valid_session
        assigns(:education).should be_a_new(Education)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Education.any_instance.stub(:save).and_return(false)
        post :create, {:education => {}}, valid_session
        response.should render_template("new")
      end
    end
  end
   describe "DELETE destroy" do
    it "destroys the requested education" do
      education = Education.create! valid_attributes
      expect {
        delete :destroy, {:id => education.to_param}, valid_session
      }.to change(Education, :count).by(-1)
    end

    it "redirects to the educations list" do
      education = Education.create! valid_attributes
      delete :destroy, {:id => education.to_param}, valid_session
      response.should redirect_to(educations_url)
    end
  end

end
