require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EmploymentHistoriesController do

  # This should return the minimal set of attributes required to create a valid
  # EmploymentHistory. As you add validations to EmploymentHistory, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EmploymentHistoriesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all employment_histories as @employment_histories" do
      employment_history = EmploymentHistory.create! valid_attributes
      get :index, {}, valid_session
      assigns(:employment_histories).should eq([employment_history])
    end
  end

  describe "GET show" do
    it "assigns the requested employment_history as @employment_history" do
      employment_history = EmploymentHistory.create! valid_attributes
      get :show, {:id => employment_history.to_param}, valid_session
      assigns(:employment_history).should eq(employment_history)
    end
  end

  describe "GET new" do
    it "assigns a new employment_history as @employment_history" do
      get :new, {}, valid_session
      assigns(:employment_history).should be_a_new(EmploymentHistory)
    end
  end

  describe "GET edit" do
    it "assigns the requested employment_history as @employment_history" do
      employment_history = EmploymentHistory.create! valid_attributes
      get :edit, {:id => employment_history.to_param}, valid_session
      assigns(:employment_history).should eq(employment_history)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new EmploymentHistory" do
        expect {
          post :create, {:employment_history => valid_attributes}, valid_session
        }.to change(EmploymentHistory, :count).by(1)
      end

      it "assigns a newly created employment_history as @employment_history" do
        post :create, {:employment_history => valid_attributes}, valid_session
        assigns(:employment_history).should be_a(EmploymentHistory)
        assigns(:employment_history).should be_persisted
      end

      it "redirects to the created employment_history" do
        post :create, {:employment_history => valid_attributes}, valid_session
        response.should redirect_to(EmploymentHistory.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved employment_history as @employment_history" do
        # Trigger the behavior that occurs when invalid params are submitted
        EmploymentHistory.any_instance.stub(:save).and_return(false)
        post :create, {:employment_history => {}}, valid_session
        assigns(:employment_history).should be_a_new(EmploymentHistory)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        EmploymentHistory.any_instance.stub(:save).and_return(false)
        post :create, {:employment_history => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested employment_history" do
        employment_history = EmploymentHistory.create! valid_attributes
        # Assuming there are no other employment_histories in the database, this
        # specifies that the EmploymentHistory created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        EmploymentHistory.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => employment_history.to_param, :employment_history => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested employment_history as @employment_history" do
        employment_history = EmploymentHistory.create! valid_attributes
        put :update, {:id => employment_history.to_param, :employment_history => valid_attributes}, valid_session
        assigns(:employment_history).should eq(employment_history)
      end

      it "redirects to the employment_history" do
        employment_history = EmploymentHistory.create! valid_attributes
        put :update, {:id => employment_history.to_param, :employment_history => valid_attributes}, valid_session
        response.should redirect_to(employment_history)
      end
    end

    describe "with invalid params" do
      it "assigns the employment_history as @employment_history" do
        employment_history = EmploymentHistory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EmploymentHistory.any_instance.stub(:save).and_return(false)
        put :update, {:id => employment_history.to_param, :employment_history => {}}, valid_session
        assigns(:employment_history).should eq(employment_history)
      end

      it "re-renders the 'edit' template" do
        employment_history = EmploymentHistory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EmploymentHistory.any_instance.stub(:save).and_return(false)
        put :update, {:id => employment_history.to_param, :employment_history => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested employment_history" do
      employment_history = EmploymentHistory.create! valid_attributes
      expect {
        delete :destroy, {:id => employment_history.to_param}, valid_session
      }.to change(EmploymentHistory, :count).by(-1)
    end

    it "redirects to the employment_histories list" do
      employment_history = EmploymentHistory.create! valid_attributes
      delete :destroy, {:id => employment_history.to_param}, valid_session
      response.should redirect_to(employment_histories_url)
    end
  end

end
